# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY code/requirements.txt /app/requirements.txt

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . /app

# Install OpenCV and other dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install pillow-heif for handling HEIC images
RUN pip install pillow-heif

# Expose port 8000 if needed (optional)
# EXPOSE 8000

# Command to run your script (adjust as needed)
CMD ["python", "code/read_palm.py", "--input", "input/hand1.jpg"]
